/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapap;

/**
 *
 * @author FilipeC
 */
public class Escolha_ADMIN extends javax.swing.JDialog {

    /**
     * Creates new form Escolha_ADMIN
     */
    public Escolha_ADMIN(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Menu administrador");
        app = new NewJDialog_app_admin(null, modal);
        verLoc = new NewJDialog_ver_locais(null, modal);
        R1 = new NewJDialog_Ins_Locais(null, modal);
        verPerc = new NewJDialog_ver_Perc(null, modal);
        InsPerc = new NewJDialog_Ins_Perc(null, modal);
        elperc = new NewJDialog_Eliminar_Percursos(null, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_I_L = new javax.swing.JButton();
        jButton_V_e_A_LOC = new javax.swing.JButton();
        jButton_Ins_Perc = new javax.swing.JButton();
        jButton_V_e_A_perc = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Eli_Perc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_I_L.setText("Inserir Locais");
        jButton_I_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_I_LActionPerformed(evt);
            }
        });

        jButton_V_e_A_LOC.setText("Ver/alterar Locais");
        jButton_V_e_A_LOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_V_e_A_LOCActionPerformed(evt);
            }
        });

        jButton_Ins_Perc.setText("Inserir percursos");
        jButton_Ins_Perc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ins_PercActionPerformed(evt);
            }
        });

        jButton_V_e_A_perc.setText("Ver/alterar percursos");
        jButton_V_e_A_perc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_V_e_A_percActionPerformed(evt);
            }
        });

        jButton_Back.setText("Voltar Login");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        jButton_Eli_Perc.setText("Eliminar percursos");
        jButton_Eli_Perc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Eli_PercActionPerformed(evt);
            }
        });

        jButton1.setText("APP de Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton_Eli_Perc, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addComponent(jButton_V_e_A_LOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_I_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Ins_Perc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_V_e_A_perc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jButton_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_I_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_V_e_A_LOC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Eli_Perc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_V_e_A_perc)
                .addGap(18, 18, 18)
                .addComponent(jButton_Ins_Perc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_I_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_I_LActionPerformed
        this.setVisible(false);
        R1.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_I_LActionPerformed

    private void jButton_V_e_A_LOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_V_e_A_LOCActionPerformed
        this.setVisible(false);
        verLoc.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_V_e_A_LOCActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_V_e_A_percActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_V_e_A_percActionPerformed
        this.setVisible(false);
        verPerc.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_V_e_A_percActionPerformed

    private void jButton_Ins_PercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ins_PercActionPerformed
        this.setVisible(false);
        InsPerc.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_Ins_PercActionPerformed

    private void jButton_Eli_PercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Eli_PercActionPerformed
        this.setVisible(false);
        elperc.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_Eli_PercActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        app.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escolha_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escolha_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escolha_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escolha_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Escolha_ADMIN dialog = new Escolha_ADMIN(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Eli_Perc;
    private javax.swing.JButton jButton_I_L;
    private javax.swing.JButton jButton_Ins_Perc;
    private javax.swing.JButton jButton_V_e_A_LOC;
    private javax.swing.JButton jButton_V_e_A_perc;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    NewJDialog_app_admin app;
    NewJDialog_Ins_Locais R1;
    NewJDialog_ver_locais verLoc;
    NewJDialog_ver_Perc verPerc;
    NewJDialog_Ins_Perc InsPerc;
    NewJDialog_Eliminar_Percursos elperc;

}
