/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapap;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author FilipeC
 */
public class NewJDialog_ver_locais extends javax.swing.JDialog {
@Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(900, 235, 620, 579); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form NewJDialog_ver_locais
     */
    public NewJDialog_ver_locais(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Ver locais");
        try {
            Javapap.ligacao = DriverManager.getConnection("jdbc:mysql://localhost:3306/javapap", "root", "");
            Javapap.expressao = Javapap.ligacao.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Cidade = new javax.swing.JTextField();
        jTextField_Local = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_cleam = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_right = new javax.swing.JButton();
        jButton_left = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jComboBox_Reg = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jButton_bvack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Cidade);
        jTextField_Cidade.setBounds(260, 160, 158, 24);
        getContentPane().add(jTextField_Local);
        jTextField_Local.setBounds(260, 200, 158, 24);

        jLabel1.setText("Região");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 120, 39, 16);

        jLabel2.setText("Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 160, 39, 16);

        jLabel3.setText("Local");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 210, 31, 16);

        jButton_cleam.setText("Limpar");
        jButton_cleam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cleamActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cleam);
        jButton_cleam.setBounds(300, 300, 70, 32);

        jButton_alterar.setText("Alterar");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_alterar);
        jButton_alterar.setBounds(160, 370, 69, 32);

        jButton_right.setText("»");
        jButton_right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rightActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_right);
        jButton_right.setBounds(420, 240, 37, 32);

        jButton_left.setText("«");
        jButton_left.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_leftActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_left);
        jButton_left.setBounds(230, 250, 37, 32);

        jButton_update.setText("Atualizar");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update);
        jButton_update.setBounds(460, 20, 80, 32);

        jComboBox_Reg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norte", "Centro", "Sul" }));
        jComboBox_Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_RegActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Reg);
        jComboBox_Reg.setBounds(260, 110, 152, 26);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(326, 148, 47, 11);

        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 100, 11, 16);

        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ID);
        jTextField_ID.setBounds(270, 80, 135, 24);

        jButton_bvack.setText("Voltar para o menu");
        jButton_bvack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bvackActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_bvack);
        jButton_bvack.setBounds(410, 370, 138, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Filipe Correia\\Desktop\\D._Pedro_IV_Porto.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 650, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_leftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_leftActionPerformed
        try {
            if (!Javapap.resultado.isFirst()) {
                Javapap.resultado.previous();
                jTextField_Cidade.setText(Javapap.resultado.getString("Cidades_Reg"));
                jTextField_Local.setText(Javapap.resultado.getString("Local"));
                jComboBox_Reg.setSelectedItem(Javapap.resultado.getObject("Regiao"));
                jTextField_ID.setText(Javapap.resultado.getString("ID"));
                Javapap.ID = jTextField_ID.getText();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar base de dados" + ex);
        }
    }//GEN-LAST:event_jButton_leftActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        jTextField_Cidade.setEnabled(false);
        jTextField_Local.setEnabled(false);
        jComboBox_Reg.setEnabled(false);
        jTextField_ID.setEnabled(false);

        try {
            Javapap.sql = "SELECT * FROM local";
            Javapap.resultado = Javapap.expressao.executeQuery(Javapap.sql);
            Javapap.resultado.next();
            jTextField_Cidade.setText(Javapap.resultado.getString("Cidades_Reg"));
            jTextField_Local.setText(Javapap.resultado.getString("Local"));
            jComboBox_Reg.setSelectedItem(Javapap.resultado.getObject("Regiao"));
            jTextField_ID.setText(Javapap.resultado.getString("ID"));
            Javapap.ID = jTextField_ID.getText();

        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rightActionPerformed
        try {
            if (!Javapap.resultado.isLast()) {
                Javapap.resultado.next();
                jTextField_Cidade.setText(Javapap.resultado.getString("Cidades_Reg"));
                jTextField_Local.setText(Javapap.resultado.getString("Local"));
                jComboBox_Reg.setSelectedItem(Javapap.resultado.getObject("Regiao"));
                jTextField_ID.setText(Javapap.resultado.getString("ID"));
                Javapap.ID = jTextField_ID.getText();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar base de dados" + ex);
        }
    }//GEN-LAST:event_jButton_rightActionPerformed

    private void jButton_cleamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cleamActionPerformed
        jTextField_Cidade.setEnabled(true);
        jTextField_Local.setEnabled(true);
        jComboBox_Reg.setEnabled(true);
    }//GEN-LAST:event_jButton_cleamActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
        try {
            String Reg = jComboBox_Reg.getSelectedItem().toString();
            String Cidade = jTextField_Cidade.getText();
            String Local = jTextField_Local.getText();

            String SQL1 = "UPDATE local SET Regiao = '" + Reg + "' WHERE ID = '" + Javapap.ID + "';";
            String SQL2 = "UPDATE local SET Cidades_Reg = '" + Cidade + "' WHERE ID = '" + Javapap.ID + "';";
            String SQL3 = "UPDATE local SET Local = '" + Local + "' WHERE ID = '" + Javapap.ID + "';";
            Javapap.expressao.executeUpdate(SQL1);
            Javapap.expressao.executeUpdate(SQL2);
            Javapap.expressao.executeUpdate(SQL3);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jTextField_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CidadeActionPerformed

    private void jComboBox_RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_RegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_RegActionPerformed

    private void jButton_bvackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bvackActionPerformed
        dispose();

    }//GEN-LAST:event_jButton_bvackActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_locais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_locais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_locais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_locais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog_ver_locais dialog = new NewJDialog_ver_locais(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_bvack;
    private javax.swing.JButton jButton_cleam;
    private javax.swing.JButton jButton_left;
    private javax.swing.JButton jButton_right;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_Reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_Cidade;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Local;
    // End of variables declaration//GEN-END:variables
}
