/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapap;

import java.util.Properties;
import javax.mail.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Filipe Correia
 */
public class NewJDialog_Login extends javax.swing.JDialog {

    @Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(900, 235, 539, 380); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form NewJDialog_Login
     */
    public NewJDialog_Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // String boas = "4.999999";

        //Math.round(Float.parseFloat(boas), 2);
        this.setTitle("Login");
        pass1 = new NewJDialog_Forgot_Password(null, modal);
        RR = new NewJDialog_Register(null, modal);
        APP = new NewJDialog_APP(null, modal);
        ADMIN = new Escolha_ADMIN(null, modal);
        USER = new Escolha_USER(null, modal);
        try {

            Javapap.ligacao = DriverManager.getConnection("jdbc:mysql://localhost:3306/javapap", "root", "");
            Javapap.expressao = Javapap.ligacao.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jTextField_Email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Login = new javax.swing.JButton();
        jButton_Forgot_Password = new javax.swing.JButton();
        jButton_Register = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 57, 86, 16);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 104, 100, 16);

        jPasswordField_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PassActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_Pass);
        jPasswordField_Pass.setBounds(154, 101, 213, 22);
        getContentPane().add(jTextField_Email);
        jTextField_Email.setBounds(154, 53, 213, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 0, 156, 35);

        jButton_Login.setText("Login");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Login);
        jButton_Login.setBounds(116, 190, 250, 41);

        jButton_Forgot_Password.setText("Esqueci-me da minha palavra passe");
        jButton_Forgot_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Forgot_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Forgot_Password);
        jButton_Forgot_Password.setBounds(122, 293, 241, 40);

        jButton_Register.setText("Registar");
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Register);
        jButton_Register.setBounds(116, 243, 247, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapap/360_F_355607062_zYMS8jaz4SfoykpWz5oViRVKL32IabTP.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 540, 380);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 220, 77, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton_Forgot_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Forgot_PasswordActionPerformed
        this.setVisible(false);
        pass1.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_Forgot_PasswordActionPerformed

    private void jPasswordField_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PassActionPerformed

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        this.setVisible(false);
        RR.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed

        //E576c71b236f$aa
        String Email1 = jTextField_Email.getText();
        String Passs = jPasswordField_Pass.getText();
        String Email_m = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
        String Pass_m = "(?=^.{8,}$)(?=.*\\d)(?=.*[!@#$%^&*]+)(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$";
        if ((Email1.matches(Email_m))) {
            if ((Passs.matches(Pass_m))) {
                try {
                    String a = "filipeaguilar01@gmail.com";
                    String email = jTextField_Email.getText();

                    String SQL_PP = "SELECT Pass from login where email = '" + email + "';";
                    Javapap.resultado = Javapap.expressao.executeQuery(SQL_PP);
                    Javapap.resultado.next();
                    String pass = Javapap.resultado.getString("Pass");

                    Criptografia.des(pass);
                    if ((!Email1.equals(email)) || (!Passs.equals(Javapap.decoded))) {
                        JOptionPane.showMessageDialog(null, "email ou password incorretos");
                    } else {

                        String sql = "SELECT * from login where email = '" + email + "';";
                        Javapap.resultado = Javapap.expressao.executeQuery(sql);
                        Javapap.resultado.next();
                        String bc = Javapap.resultado.getString("email");
                        if (Javapap.decoded.equals(Passs)) {
                            if (bc.equals(Email1)) {
                                if (Javapap.resultado != null) {
                                    Javapap.Email = email;
                                    String sql2 = "Select ID_user from user where email = '" + bc + "';";
                                    Javapap.resultado = Javapap.expressao.executeQuery(sql2);
                                    Javapap.resultado.next();
                                    Javapap.IDU = Javapap.resultado.getString("ID_user");
                                    jTextField_Email.setText("");
                                    jPasswordField_Pass.setText("");
                                    if (Javapap.Email.equals(a)) {
                                        this.setVisible(false);
                                        ADMIN.setVisible(true);
                                        this.setVisible(true);
                                    } else {
                                        this.setVisible(false);
                                        USER.setVisible(true);
                                        this.setVisible(true);
                                    }
                                } else {
                                    Javapap.resultado.next();
                                    JOptionPane.showMessageDialog(null, Javapap.resultado.getString("email"));
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Pass ou email incorretos");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Pass ou email incorretos");
                        }

                        //filipeaguilar01@gmail.com
                        //E576c71b236f$aa
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Verifique o email e a pass");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique o email e a pass");
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog_Login dialog = new NewJDialog_Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Forgot_Password;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JTextField jTextField_Email;
    // End of variables declaration//GEN-END:variables

    NewJDialog_Register RR;
    Escolha_ADMIN ADMIN;
    Escolha_USER USER;
    NewJDialog_Forgot_Password pass1;
    NewJDialog_APP APP;
}
