/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapap;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author FilipeC
 */
public class NewJDialog_Ins_Perc extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog_Ins_Perc
     */
    public NewJDialog_Ins_Perc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Inserir percursos");
        try {
            Javapap.ligacao = DriverManager.getConnection("jdbc:mysql://localhost:3306/javapap", "root", "");
            Javapap.expressao = Javapap.ligacao.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NomePerc = new javax.swing.JTextField();
        jTextField_Cidade = new javax.swing.JTextField();
        jTextField_Dist = new javax.swing.JTextField();
        jButton_Ins = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome percurso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(42, 50, 88, 16);

        jLabel2.setText("Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 92, 88, 16);

        jLabel3.setText("Distância");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 134, 88, 16);
        getContentPane().add(jTextField_NomePerc);
        jTextField_NomePerc.setBounds(136, 46, 137, 24);
        getContentPane().add(jTextField_Cidade);
        jTextField_Cidade.setBounds(136, 88, 137, 24);
        getContentPane().add(jTextField_Dist);
        jTextField_Dist.setBounds(136, 130, 137, 24);

        jButton_Ins.setText("Inserir");
        jButton_Ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Ins);
        jButton_Ins.setBounds(149, 172, 67, 32);

        jButton_Back.setText("Voltar ao menu");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Back);
        jButton_Back.setBounds(278, 262, 116, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Filipe Correia\\Desktop\\1-20-4-800x600.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsActionPerformed
        try {
            String a = "";

            String NomePerc = jTextField_NomePerc.getText();
            String Cidade = jTextField_Cidade.getText();
            String Distancia = jTextField_Dist.getText();
            String SQL = "INSERT INTO percursos (ID_Percurso, Nome_perc, ID, Cidade, Km) VALUES (NULL, '"+NomePerc+"', '2', '"+Cidade+"', '"+Distancia+"');";
            Javapap.expressao.executeUpdate(SQL);
            String SQL1 = "Select ID_Percurso from percursos where Nome_perc = '"+NomePerc+"';";
            Javapap.resultado = Javapap.expressao.executeQuery(SQL1);
            Javapap.resultado.next();
            Javapap.ID = Javapap.resultado.getString(1);
            jTextField_Cidade.setText(a);
            jTextField_NomePerc.setText(a);
            jTextField_Dist.setText(a);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton_InsActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Ins_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Ins_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Ins_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_Ins_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog_Ins_Perc dialog = new NewJDialog_Ins_Perc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Ins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField_Cidade;
    private javax.swing.JTextField jTextField_Dist;
    private javax.swing.JTextField jTextField_NomePerc;
    // End of variables declaration//GEN-END:variables
}
