/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapap;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author FilipeC
 */
public class NewJDialog_ver_Perc extends javax.swing.JDialog {
@Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(900, 235, 490, 320); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form NewJDialog_ver_Perc
     */
    public NewJDialog_ver_Perc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Ver percursos");
        try {
            Javapap.ligacao = DriverManager.getConnection("jdbc:mysql://localhost:3306/javapap", "root", "");
            Javapap.expressao = Javapap.ligacao.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_NomePerc = new javax.swing.JTextField();
        jTextField2_Cidade = new javax.swing.JTextField();
        jTextField_Dist = new javax.swing.JTextField();
        jButtonleft = new javax.swing.JButton();
        jButtonright = new javax.swing.JButton();
        jButton_clean = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nome percurso");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(42, 75, 88, 16);

        jLabel2.setText("Cidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(42, 117, 88, 16);

        jLabel3.setText("Distancia");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 159, 88, 16);
        getContentPane().add(jTextField_NomePerc);
        jTextField_NomePerc.setBounds(136, 71, 140, 24);
        getContentPane().add(jTextField2_Cidade);
        jTextField2_Cidade.setBounds(136, 113, 140, 24);
        getContentPane().add(jTextField_Dist);
        jTextField_Dist.setBounds(136, 155, 140, 24);

        jButtonleft.setText("«");
        jButtonleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonleftActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonleft);
        jButtonleft.setBounds(126, 191, 37, 32);

        jButtonright.setText("»");
        jButtonright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrightActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonright);
        jButtonright.setBounds(202, 191, 37, 32);

        jButton_clean.setText("Limpar");
        jButton_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cleanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_clean);
        jButton_clean.setBounds(152, 235, 70, 32);

        jButton_alterar.setText("Alterar");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_alterar);
        jButton_alterar.setBounds(158, 654, 69, 32);

        jButton_update.setText("Atualizar");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update);
        jButton_update.setBounds(781, 6, 80, 32);

        jButton_back.setText("Voltar ao menu");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_back);
        jButton_back.setBounds(794, 648, 116, 32);

        jLabel4.setText("ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(42, 45, 20, 16);
        getContentPane().add(jTextField_ID);
        jTextField_ID.setBounds(136, 41, 140, 24);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Filipe Correia\\Desktop\\Passeio-pedestre-1.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 480, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cleanActionPerformed
        jTextField2_Cidade.setEnabled(true);
        jTextField_Dist.setEnabled(true);
        jTextField_NomePerc.setEnabled(true);
    }//GEN-LAST:event_jButton_cleanActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        jTextField_Dist.setEnabled(false);
        jTextField_NomePerc.setEnabled(false);
        jTextField2_Cidade.setEnabled(false);
        jTextField_ID.setEnabled(false);

        try {
            Javapap.sql = "SELECT * FROM percursos";
            Javapap.resultado = Javapap.expressao.executeQuery(Javapap.sql);
            Javapap.resultado.next();
            jTextField_Dist.setText(Javapap.resultado.getString("Km"));
            jTextField_NomePerc.setText(Javapap.resultado.getString("Nome_perc"));
            jTextField2_Cidade.setText(Javapap.resultado.getString("Cidade"));
            jTextField_ID.setText(Javapap.resultado.getString("ID_Percurso"));
            Javapap.ID2 = jTextField_ID.getText();

        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButtonrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrightActionPerformed
        try {
            if (!Javapap.resultado.isLast()) {
                Javapap.resultado.next();
                jTextField_Dist.setText(Javapap.resultado.getString("Km"));
                jTextField_NomePerc.setText(Javapap.resultado.getString("Nome_perc"));
                jTextField2_Cidade.setText(Javapap.resultado.getString("Cidade"));
                jTextField_ID.setText(Javapap.resultado.getString("ID_Percurso"));
                Javapap.ID2 = jTextField_ID.getText();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar base de dados" + ex);
        }
    }//GEN-LAST:event_jButtonrightActionPerformed

    private void jButtonleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonleftActionPerformed
        try {
            if (!Javapap.resultado.isFirst()) {
                Javapap.resultado.previous();
                jTextField_Dist.setText(Javapap.resultado.getString("Km"));
                jTextField_NomePerc.setText(Javapap.resultado.getString("Nome_perc"));
                jTextField2_Cidade.setText(Javapap.resultado.getString("Cidade"));
                jTextField_ID.setText(Javapap.resultado.getString("ID_Percurso"));
                Javapap.ID2 = jTextField_ID.getText();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar base de dados" + ex);
        }
    }//GEN-LAST:event_jButtonleftActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
          try {
            String NomePerc = jTextField_NomePerc.getText();
            String Cidade = jTextField2_Cidade.getText();
            String Dist = jTextField_Dist.getText();

            String SQL1 = "UPDATE percursos SET Km = '" + Dist + "' WHERE ID = '" + Javapap.ID2 + "';";
            String SQL2 = "UPDATE percursos SET Cidade = '" + Cidade + "' WHERE ID = '" + Javapap.ID2 + "';";
            String SQL3 = "UPDATE percursos SET Nome_perc = '" + NomePerc + "' WHERE ID = '" + Javapap.ID2 + "';";
            Javapap.expressao.executeUpdate(SQL1);
            Javapap.expressao.executeUpdate(SQL2);
            Javapap.expressao.executeUpdate(SQL3);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog_ver_Perc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog_ver_Perc dialog = new NewJDialog_ver_Perc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_clean;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButtonleft;
    private javax.swing.JButton jButtonright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField2_Cidade;
    private javax.swing.JTextField jTextField_Dist;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_NomePerc;
    // End of variables declaration//GEN-END:variables
}
